#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Jan 05, 2021 07:01:48 AM +03  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black
    wm focusmodel $top passive
    wm geometry $top 620x385+881+507
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2948 1181
    wm minsize $top 130 10
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Kcalibrator"
    vTcl:DefineAlias "$top" "Toplevel" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab48 \
        \
        -font {-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -text {Pattern configuration} \
        -background $vTcl(actual_gui_bg) -height 235 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 360
    vTcl:DefineAlias "$top.lab48" "lf_PatternConfig" vTcl:WidgetProc "Toplevel" 1
    set site_3_0 $top.lab48
    ttk::label $site_3_0.tLa59 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Start, stop and step values for K-factor calibration}
    vTcl:DefineAlias "$site_3_0.tLa59" "_lbl_StartStopStep" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn60 \
        \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {} -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn60" "ent_StartK" vTcl:WidgetProc "Toplevel" 1
    vTcl:copy_lock $site_3_0.tEn60
    ttk::entry $site_3_0.tEn61 \
        \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {} -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn61" "ent_StepK" vTcl:WidgetProc "Toplevel" 1
    vTcl:copy_lock $site_3_0.tEn61
    ttk::label $site_3_0.tLa63 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text {From K = }
    vTcl:DefineAlias "$site_3_0.tLa63" "_lbl_KFrom" vTcl:WidgetProc "Toplevel" 1
    vTcl:copy_lock $site_3_0.tLa63
    ttk::label $site_3_0.tLa64 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text {to K = }
    vTcl:DefineAlias "$site_3_0.tLa64" "_lbl_KTo" vTcl:WidgetProc "Toplevel" 1
    vTcl:copy_lock $site_3_0.tLa64
    ttk::label $site_3_0.tLa65 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text {change by }
    vTcl:DefineAlias "$site_3_0.tLa65" "_lbl_KBy" vTcl:WidgetProc "Toplevel" 1
    vTcl:copy_lock $site_3_0.tLa65
    ttk::label $site_3_0.tLa66 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text {Fast speed}
    vTcl:DefineAlias "$site_3_0.tLa66" "_lbl_FastSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn67 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn67" "ent_FastSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa68 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text {Slow speed}
    vTcl:DefineAlias "$site_3_0.tLa68" "_lbl_SlowSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn69 \
        \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {} -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn69" "ent_SlowSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa70 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Speed values for pattern generation}
    vTcl:DefineAlias "$site_3_0.tLa70" "_lbl_Speeds" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa71 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Number of layers printed with any specific K-factor}
    vTcl:DefineAlias "$site_3_0.tLa71" "_lbl_LayersPerK" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn72 \
        \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {} -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn72" "ent_StopK" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn73 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn73" "ent_LayersPerK" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn74 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn74" "ent_SpdFr1" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn75 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn75" "ent_SpdFr2" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn76 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn76" "ent_SpdFr3" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa78 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Fractions for pattern paths}
    vTcl:DefineAlias "$site_3_0.tLa78" "_lbl_SpeedFractions" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa79 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Size of the pattern (XxYxZ): }
    vTcl:DefineAlias "$site_3_0.tLa79" "_lbl_PatternSize" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa82 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text x
    vTcl:DefineAlias "$site_3_0.tLa82" "_lbl_psx" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn83 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn83" "ent_PatternXsize" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn84 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn84" "ent_PatternYsize" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa85 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text {x 100 mm}
    vTcl:DefineAlias "$site_3_0.tLa85" "lbl_PatternZsize" vTcl:WidgetProc "Toplevel" 1
    checkbutton $site_3_0.che50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left \
        -text {Print pattern with two perimeters instead of one} \
        -variable che50
    vTcl:DefineAlias "$site_3_0.che50" "chk_TwoPerimeters" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa51 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm/s
    vTcl:DefineAlias "$site_3_0.tLa51" "_lbl_unitsFastSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa53 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm/s
    vTcl:DefineAlias "$site_3_0.tLa53" "_lbl_unitsSlowSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::separator $site_3_0.tSe70
    vTcl:DefineAlias "$site_3_0.tSe70" "TSeparator1" vTcl:WidgetProc "Toplevel" 1
    ttk::separator $site_3_0.tSe72
    vTcl:DefineAlias "$site_3_0.tSe72" "TSeparator2" vTcl:WidgetProc "Toplevel" 1
    place $site_3_0.tLa59 \
        -in $site_3_0 -x 5 -y 20 -width 299 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn60 \
        -in $site_3_0 -x 68 -y 45 -width 55 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn61 \
        -in $site_3_0 -x 299 -y 45 -width 55 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa63 \
        -in $site_3_0 -x 5 -y 45 -width 60 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa64 \
        -in $site_3_0 -x 126 -y 45 -width 40 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa65 \
        -in $site_3_0 -x 229 -y 45 -width 65 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa66 \
        -in $site_3_0 -x 5 -y 125 -width 70 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn67 \
        -in $site_3_0 -x 77 -y 125 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa68 \
        -in $site_3_0 -x 188 -y 125 -width 75 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn69 \
        -in $site_3_0 -x 260 -y 125 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa70 \
        -in $site_3_0 -x 5 -y 100 -width 325 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa71 \
        -in $site_3_0 -x 5 -y 70 -width 305 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn72 \
        -in $site_3_0 -x 170 -y 45 -width 55 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn73 \
        -in $site_3_0 -x 314 -y 70 -width 40 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn74 \
        -in $site_3_0 -x 172 -y 150 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn75 \
        -in $site_3_0 -x 238 -y 150 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn76 \
        -in $site_3_0 -x 304 -y 150 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa78 \
        -in $site_3_0 -x 5 -y 150 -width 160 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa79 \
        -in $site_3_0 -x 5 -y 185 -width 160 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa82 \
        -in $site_3_0 -x 219 -y 185 -width 10 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn83 \
        -in $site_3_0 -x 167 -y 185 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn84 \
        -in $site_3_0 -x 231 -y 185 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa85 \
        -in $site_3_0 -x 284 -y 185 -width 70 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.che50 \
        -in $site_3_0 -x 5 -y 210 -width 300 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa51 \
        -in $site_3_0 -x 130 -y 125 -width 40 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa53 \
        -in $site_3_0 -x 310 -y 125 -width 40 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tSe70 \
        -in $site_3_0 -x 0 -relx -0.011 -y 76 -width 0 -relwidth 1.011 \
        -anchor nw -bordermode inside
    place $site_3_0.tSe72 \
        -in $site_3_0 -x 0 -relx -0.017 -y 158 -width 0 -relwidth 1.028 \
        -anchor nw -bordermode inside
    labelframe $top.lab53 \
        \
        -font {-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -text {Machine configuration} \
        -background $vTcl(actual_gui_bg) -height 125 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 360
    vTcl:DefineAlias "$top.lab53" "lf_MachineConfig" vTcl:WidgetProc "Toplevel" 1
    set site_3_0 $top.lab53
    ttk::label $site_3_0.tLa87 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text Kinematics
    vTcl:DefineAlias "$site_3_0.tLa87" "_lbl_Kinematics" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $site_3_0.tCo88 \
        -values {Cartesian Delta} \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {}
    vTcl:DefineAlias "$site_3_0.tCo88" "cmb_Kinematics" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa89 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text Firmware
    vTcl:DefineAlias "$site_3_0.tLa89" "_lbl_FIimware" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $site_3_0.tCo90 \
        -values {Marlin Klipper RepRapFirmware} \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {}
    vTcl:DefineAlias "$site_3_0.tCo90" "cmb_Firmware" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa91 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Build volume: }
    vTcl:DefineAlias "$site_3_0.tLa91" "_lbl_BuildVol" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn92 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn92" "ent_BuildVolY" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn94 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn94" "ent_BuildVolX" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa95 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text x
    vTcl:DefineAlias "$site_3_0.tLa95" "_lbl_bvx1" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa96 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text x
    vTcl:DefineAlias "$site_3_0.tLa96" "lbl_bvx2_units" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa97 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm
    vTcl:DefineAlias "$site_3_0.tLa97" "lbl_bvx3_units" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $site_3_0.tCo46 \
        -values {G29 M83} \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {}
    vTcl:DefineAlias "$site_3_0.tCo46" "cmb_AutolevelingType" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa47 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Autoleveling type}
    vTcl:DefineAlias "$site_3_0.tLa47" "_lbl_AutolevelingType" vTcl:WidgetProc "Toplevel" 1
    checkbutton $site_3_0.che48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Use autoleveling} -variable che48
    vTcl:DefineAlias "$site_3_0.che48" "chk_UseAutoleveling" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn49 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn49" "ent_BuildVolZ" vTcl:WidgetProc "Toplevel" 1
    place $site_3_0.tLa87 \
        -in $site_3_0 -x 5 -y 25 -width 70 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tCo88 \
        -in $site_3_0 -x 75 -y 25 -width 103 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa89 \
        -in $site_3_0 -x 190 -y 25 -width 60 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tCo90 \
        -in $site_3_0 -x 250 -y 25 -width 103 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa91 \
        -in $site_3_0 -x 5 -y 60 -width 90 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn92 \
        -in $site_3_0 -x 160 -y 60 -width 55 -height 20 -anchor nw \
        -bordermode ignore
    place $site_3_0.tEn94 \
        -in $site_3_0 -x 90 -y 60 -width 55 -height 20 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa95 \
        -in $site_3_0 -x 147 -y 60 -width 10 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa96 \
        -in $site_3_0 -x 217 -y 55 -width 120 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa97 \
        -in $site_3_0 -x 290 -y 60 -width 30 -relwidth 0 -height 22 \
        -anchor nw -bordermode ignore
    place $site_3_0.tCo46 \
        -in $site_3_0 -x 280 -y 90 -width 73 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa47 \
        -in $site_3_0 -x 170 -y 90 -width 105 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.che48 \
        -in $site_3_0 -x 5 -y 90 -height 22 -relheight 0 -anchor nw \
        -bordermode ignore
    place $site_3_0.tEn49 \
        -in $site_3_0 -x 229 -y 60 -width 55 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    labelframe $top.lab86 \
        \
        -font {-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -text {Print configuration} \
        -background $vTcl(actual_gui_bg) -height 335 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 230
    vTcl:DefineAlias "$top.lab86" "lf_PrintConfig" vTcl:WidgetProc "Toplevel" 1
    set site_3_0 $top.lab86
    ttk::label $site_3_0.tLa54 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Nozzle temperature}
    vTcl:DefineAlias "$site_3_0.tLa54" "_lbl_NozzleTemp" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa55 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Bed temperature}
    vTcl:DefineAlias "$site_3_0.tLa55" "_lbl_BedTemp" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn56 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn56" "ent_NozzleTemp" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn57 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn57" "ent_BedTemp" vTcl:WidgetProc "Toplevel" 1
    checkbutton $site_3_0.che58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Retract at layer change} -variable che58
    vTcl:DefineAlias "$site_3_0.che58" "chk_RetractAtLayerChange" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa59 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Retraction speed}
    vTcl:DefineAlias "$site_3_0.tLa59" "_lbl_RetractSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa60 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Retraction distance}
    vTcl:DefineAlias "$site_3_0.tLa60" "_lbl_RetractDist" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn61 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm
    vTcl:DefineAlias "$site_3_0.tEn61" "ent_RetractDist" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn62 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor fleur
    vTcl:DefineAlias "$site_3_0.tEn62" "ent_RetractSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa63 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm
    vTcl:DefineAlias "$site_3_0.tLa63" "_lbl_unitsRetractDist" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa64 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm/s
    vTcl:DefineAlias "$site_3_0.tLa64" "_lbl_unitsRetractSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa65 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text °C
    vTcl:DefineAlias "$site_3_0.tLa65" "_lbl_unitsNozzleTemp" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa66 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text °C
    vTcl:DefineAlias "$site_3_0.tLa66" "_lbl_unitsBedTemp" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa67 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text Cooling
    vTcl:DefineAlias "$site_3_0.tLa67" "_lbl_Cooling" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa69 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text 50%
    vTcl:DefineAlias "$site_3_0.tLa69" "lbl_CoolingPerc" vTcl:WidgetProc "Toplevel" 1
    ttk::separator $site_3_0.tSe73
    vTcl:DefineAlias "$site_3_0.tSe73" "TSeparator3" vTcl:WidgetProc "Toplevel" 1
    ttk::separator $site_3_0.tSe74
    vTcl:DefineAlias "$site_3_0.tSe74" "TSeparator4" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa75 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {First layer speed}
    vTcl:DefineAlias "$site_3_0.tLa75" "_lbl_FirstLayerSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa76 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Travel speed}
    vTcl:DefineAlias "$site_3_0.tLa76" "_lbl_TravelSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa77 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text {Line width}
    vTcl:DefineAlias "$site_3_0.tLa77" "_lbl_LineWidth" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa78 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Layer height}
    vTcl:DefineAlias "$site_3_0.tLa78" "_lbl_LayerHeight" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa79 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 \
        -text {Filament diameter}
    vTcl:DefineAlias "$site_3_0.tLa79" "_lbl_FilamentDia" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn80 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor fleur
    vTcl:DefineAlias "$site_3_0.tEn80" "ent_FirstLayerSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn81 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor fleur
    vTcl:DefineAlias "$site_3_0.tEn81" "ent_TravelSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::separator $site_3_0.tSe82
    vTcl:DefineAlias "$site_3_0.tSe82" "TSeparator5" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn83 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor fleur
    vTcl:DefineAlias "$site_3_0.tEn83" "ent_LineWidth" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn84 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor fleur
    vTcl:DefineAlias "$site_3_0.tEn84" "ent_LayerHeight" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn85 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor fleur
    vTcl:DefineAlias "$site_3_0.tEn85" "ent_FilamentDia" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa87 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm
    vTcl:DefineAlias "$site_3_0.tLa87" "_lbl_unitsLineWidth" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa88 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm
    vTcl:DefineAlias "$site_3_0.tLa88" "_lbl_unitsLayerHeight" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa89 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm
    vTcl:DefineAlias "$site_3_0.tLa89" "_lbl_unitsFilamentDia" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa92 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm
    vTcl:DefineAlias "$site_3_0.tLa92" "_lbl_unitsFirstLayerSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa93 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm
    vTcl:DefineAlias "$site_3_0.tLa93" "_lbl_unitsTravelSpeed" vTcl:WidgetProc "Toplevel" 1
    ttk::scale $site_3_0.tSc45 \
        -to 100 -value 50 -length 20 -takefocus {}
    vTcl:DefineAlias "$site_3_0.tSc45" "scl_CoolingPerc" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa45 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text {Z offset}
    vTcl:DefineAlias "$site_3_0.tLa45" "_lbl_Zoffset" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_3_0.tLa46 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -takefocus 0 -text mm
    vTcl:DefineAlias "$site_3_0.tLa46" "_lbl_unitsZoffset" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_3_0.tEn47 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor fleur
    vTcl:DefineAlias "$site_3_0.tEn47" "ent_Zoffset" vTcl:WidgetProc "Toplevel" 1
    place $site_3_0.tLa54 \
        -in $site_3_0 -x 5 -y 20 -width 120 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa55 \
        -in $site_3_0 -x 5 -y 45 -width 105 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn56 \
        -in $site_3_0 -x 130 -y 20 -width 55 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn57 \
        -in $site_3_0 -x 130 -y 45 -width 55 -height 20 -anchor nw \
        -bordermode ignore
    place $site_3_0.che58 \
        -in $site_3_0 -x 5 -y 150 -width 155 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa59 \
        -in $site_3_0 -x 5 -y 125 -width 120 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa60 \
        -in $site_3_0 -x 5 -y 100 -width 120 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn61 \
        -in $site_3_0 -x 130 -y 100 -width 55 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn62 \
        -in $site_3_0 -x 130 -y 125 -width 55 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa63 \
        -in $site_3_0 -x 185 -y 100 -width 30 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa64 \
        -in $site_3_0 -x 185 -y 125 -width 40 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa65 \
        -in $site_3_0 -x 185 -y 20 -width 20 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa66 \
        -in $site_3_0 -x 185 -y 45 -width 20 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa67 \
        -in $site_3_0 -x 5 -y 70 -width 50 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa69 \
        -in $site_3_0 -x 185 -y 70 -width 40 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tSe73 \
        -in $site_3_0 -x 0 -relx -0.048 -y 76 -width 0 -relwidth 1.067 \
        -anchor nw -bordermode inside
    place $site_3_0.tSe74 \
        -in $site_3_0 -x 0 -relx -0.026 -y 158 -width 0 -relwidth 1.03 \
        -anchor nw -bordermode inside
    place $site_3_0.tLa75 \
        -in $site_3_0 -x 5 -y 185 -width 120 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa76 \
        -in $site_3_0 -x 5 -y 210 -width 120 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa77 \
        -in $site_3_0 -x 5 -y 240 -width 120 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa78 \
        -in $site_3_0 -x 5 -y 265 -width 120 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa79 \
        -in $site_3_0 -x 5 -y 290 -width 120 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tEn80 \
        -in $site_3_0 -x 130 -y 185 -width 55 -height 20 -anchor nw \
        -bordermode ignore
    place $site_3_0.tEn81 \
        -in $site_3_0 -x 130 -y 210 -width 55 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tSe82 \
        -in $site_3_0 -x 0 -relx -0.017 -y 216 -width 0 -relwidth 1.057 \
        -anchor nw -bordermode inside
    place $site_3_0.tEn83 \
        -in $site_3_0 -x 130 -y 240 -width 55 -height 20 -anchor nw \
        -bordermode ignore
    place $site_3_0.tEn84 \
        -in $site_3_0 -x 130 -y 265 -width 55 -height 20 -anchor nw \
        -bordermode ignore
    place $site_3_0.tEn85 \
        -in $site_3_0 -x 130 -y 290 -width 55 -height 20 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa87 \
        -in $site_3_0 -x 185 -y 240 -width 30 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa88 \
        -in $site_3_0 -x 185 -y 265 -width 30 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa89 \
        -in $site_3_0 -x 185 -y 290 -width 30 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa92 \
        -in $site_3_0 -x 185 -y 185 -width 30 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tLa93 \
        -in $site_3_0 -x 185 -y 210 -width 30 -height 22 -anchor nw \
        -bordermode ignore
    place $site_3_0.tSc45 \
        -in $site_3_0 -x 60 -y 73 -width 120 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa45 \
        -in $site_3_0 -x 5 -y 314 -width 120 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tLa46 \
        -in $site_3_0 -x 185 -y 314 -width 30 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tEn47 \
        -in $site_3_0 -x 130 -y 315 -width 55 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu90 \
        -takefocus {} -text {Save configuration}
    vTcl:DefineAlias "$top.tBu90" "btn_SaveConfig" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu91 \
        -takefocus {} -text {Generate G-code}
    vTcl:DefineAlias "$top.tBu91" "btn_Generate" vTcl:WidgetProc "Toplevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 10 -y 10 -width 360 -relwidth 0 -height 235 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab53 \
        -in $top -x 10 -y 250 -width 360 -relwidth 0 -height 125 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab86 \
        -in $top -x 380 -y 10 -width 230 -relwidth 0 -height 339 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu90 \
        -in $top -x 375 -y 351 -width 116 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu91 \
        -in $top -x 495 -y 351 -width 116 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore
    } ;# end vTcl:withBusyCursor

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}
