#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Jan 04, 2021 05:36:01 PM +03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    pass
    # global chk_TwoPerimeters_var
    # che50 = tk.BooleanVar()
    # global che48
    # che48 = tk.BooleanVar()
    # global che58
    # che58 = tk.BooleanVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import kcalibrator_gui
    kcalibrator_gui.vp_start_gui()

